### ISSUE TITLE
[iOS] Appstore products appear to load, but products list is empty, Appstore Plugin undefined.

### ISSUE THREAD

**Issue by jmdjr** [j3k0/cordova-plugin-purchase#1394]
### Observed behavior
```
[Log] [CdvPurchase] INFO: initialize() (user-script:13, line 321)
[Log] [CdvPurchase.Adapters] INFO: Adding platforms: [{"platform":"ios-appstore"}] (user-script:13, line 321)
[Log] [CdvPurchase.Adapters] INFO:  (user-script:13, line 321)
[Log] [CdvPurchase.Adapters] INFO: AppStore initializing... (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] INFO: bridge.init (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore.Bridge] DEBUG: setup ok (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] INFO: ready (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] INFO: bridge.init done (user-script:13, line 321)
[Log] [CdvPurchase.Adapters] INFO: AppStore initialized.  (user-script:13, line 321)
[Log] [CdvPurchase.Adapters] INFO: AppStore products: [{"id":"app.sgl.linker.iap.test.1","platform":"ios-appstore","type":"consumable"}] (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] INFO: bridge.load (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore.Bridge] DEBUG: load ["app.sgl.linker.iap.test.1"] (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore.Bridge] DEBUG: load ok: { valid:[{"id":"app.sgl.linker.iap.test.1","description":"test purchasing something","introPrice":null,"introPricePaymentMode":null,"billingPeriodUnit":"Day","countryCode":"US","introPricePeriodUnit":null,"discounts":[],"title":"SGL: Test purchase 1","price":"$0.99","billingPeriod":0,"group":null,"priceMicros":990000,"currency":"USD","introPricePeriod":null,"introPriceMicros":null}] invalid:[] } (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] INFO: bridge.loaded: {"validProducts":[{"id":"app.sgl.linker.iap.test.1","description":"test purchasing something","introPrice":null,"introPricePaymentMode":null,"billingPeriodUnit":"Day","countryCode":"US","introPricePeriodUnit":null,"discounts":[],"title":"SGL: Test purchase 1","price":"$0.99","billingPeriod":0,"group":null,"priceMicros":990000,"currency":"USD","introPricePeriod":null,"introPriceMicros":null}],"invalidProducts":[]} (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] INFO: eligibilities ready. (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] DEBUG: app.sgl.linker.iap.test.1 is valid: {"id":"app.sgl.linker.iap.test.1","description":"test purchasing something","introPrice":null,"introPricePaymentMode":null,"billingPeriodUnit":"Day","countryCode":"US","introPricePeriodUnit":null,"discounts":[],"title":"SGL: Test purchase 1","price":"$0.99","billingPeriod":0,"group":null,"priceMicros":990000,"currency":"USD","introPricePeriod":null,"introPriceMicros":null} (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] DEBUG: registering existing product (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] DEBUG: Products loaded: [{"className":"Product","title":"SGL: Test purchase 1","description":"test purchasing something","platform":"ios-appstore","type":"consumable","id":"app.sgl.linker.iap.test.1","offers":[{"className":"Offer","id":"$","pricingPhases":[{"price":"$0.99","priceMicros":990000,"currency":"USD","paymentMode":"UpFront","recurrenceMode":"NON_RECURRING"}],"productId":"app.sgl.linker.iap.test.1","productType":"consumable","platform":"ios-appstore","offerType":"Default"}],"raw":{"id":"app.sgl.linker.iap.test.1","description":"test purchasing something","introPrice":null,"introPricePaymentMode":null,"billingPeriodUnit":"Day","countryCode":"US","introPricePeriodUnit":null,"discounts":[],"title":"SGL: Test purchase 1","price":"$0.99","billingPeriod":0,"group":null,"priceMicros":990000,"currency":"USD","introPricePeriod":null,"introPriceMicros":null},"countryCode":"US"}] (user-script:13, line 321)
[Log] [CdvPurchase.Adapters] INFO: AppStore loaded: [{"className":"Product","title":"SGL: Test purchase 1","description":"test purchasing something","platform":"ios-appstore","type":"consumable","id":"app.sgl.linker.iap.test.1","offers":[{"className":"Offer","id":"$","pricingPhases":[{"price":"$0.99","priceMicros":990000,"currency":"USD","paymentMode":"UpFront","recurrenceMode":"NON_RECURRING"}],"productId":"app.sgl.linker.iap.test.1","productType":"consumable","platform":"ios-appstore","offerType":"Default"}],"raw":{"id":"app.sgl.linker.iap.test.1","description":"test purchasing something","introPrice":null,"introPricePaymentMode":null,"billingPeriodUnit":"Day","countryCode":"US","introPricePeriodUnit":null,"discounts":[],"title":"SGL: Test purchase 1","price":"$0.99","billingPeriod":0,"group":null,"priceMicros":990000,"currency":"USD","introPricePeriod":null,"introPriceMicros":null},"countryCode":"US"}] (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore.Bridge] DEBUG: processing pending transactions (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] DEBUG: loading appstore receipt... (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore.Bridge] DEBUG: loading appStoreReceipt (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore.Bridge] DEBUG: infoPlist: app.lostseraph.linker,1.0,16809984,null (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] DEBUG: appstore receipt loaded (user-script:13, line 321)
[Warning] [CdvPurchase.AppleAppStore] WARNING: no appStoreReceipt (user-script:13, line 321)
```
and on the app none of the products are visible?
after all this, everything looks great, but inspecting the appstore adapter
```
const appStore = store.getAdapter(CdvPurchase.Platform.APPLE_APPSTORE);
```
is undefined. I have In-App Purchases enabled in the XCode, and my implementation follows all the tutorials (for the most part) yet this is happening... 
          
### Expected behavior
The CdvPurchase.store.products list has the loaded products, or at least the appstore adapter reporting itself as undefined.

### System Info
XCode v 14.2
iMac MacOS Ventura 13.2.1
Capacitor v. 4.6.0 (capacitor apps are based off cordova, don't see how this would make a difference here)

**Comment by j3k0** [comment]
The list of products is empty because the App Store adapter didn't reach the "ready" state. I wonder if it will work with the integration of a receipt validation service? The use case is more broadly tested. You can try this quickly with a free account on https://www.iaptic.com/

**Comment by jmdjr** [comment]
smooth method to "recommend" your company's services... but honestly was hoping not to need any more accounts to use iap. going to test with the free account but really sad that I have to use a service to get a free component to function.

**Comment by jmdjr** [comment]
how do we integrate the receipt validation service? the documentation links:
https://www.iaptic.com/documentation/setup/ios is out of date (the images are of older ui and step 5/6 no longer exist on those pages)
and
https://www.iaptic.com/documentation/validator-url/ is straight up 404.

**Comment by jmdjr** [comment]
![image](https://user-images.githubusercontent.com/836561/226002145-184138d0-9382-40b3-99bc-3cc9490b1fe5.png)

**Comment by j3k0** [comment]
> smooth method to "recommend" your company's services... but honestly was hoping not to need any more accounts to use iap. going to test with the free account but really sad that I have to use a service to get a free component to function.

You don't have to. I'm trying to understand what doesn't work in your case. As far as I know you're the only user with this issue, so I'm trying to eliminate possible reasons.

The broken link and outdated screenshots are fixed.

**Comment by jmdjr** [comment]
I hear yea... that was rude of me. sorry. going to review the updates and see if it starts working.

**Comment by jmdjr** [comment]
```[Log] onscript loading complete (user-script:11, line 1456)
[Log] -IAP-: CdvPurchase IS defined (main.js, line 1)
[Log] -IAP-: installing iaptic receipt validator... (main.js, line 1)
[Log] -IAP-: registering products... (main.js, line 1)
[Log] -IAP-: setting up listeners... (main.js, line 1)
[Log] -IAP-: Store initializing... (main.js, line 1)
[Log] [CdvPurchase] INFO: initialize() (user-script:13, line 321)
[Log] [CdvPurchase.Adapters] INFO: Adding platforms: [{"platform":"ios-appstore"}] (user-script:13, line 321)
[Log] [CdvPurchase.Adapters] INFO:  (user-script:13, line 321)
[Log] [CdvPurchase.Adapters] INFO: AppStore initializing... (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] INFO: bridge.init (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore.Bridge] DEBUG: setup ok (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] INFO: ready (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] INFO: bridge.init done (user-script:13, line 321)
[Log] [CdvPurchase.Adapters] INFO: AppStore initialized.  (user-script:13, line 321)
[Log] [CdvPurchase.Adapters] INFO: AppStore products: [{"id":"app.sgl.linker.iap.test.1","platform":"ios-appstore","type":"consumable"}] (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] INFO: bridge.load (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore.Bridge] DEBUG: load ["app.sgl.linker.iap.test.1"] (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore.Bridge] DEBUG: load ok: { valid:[{"id":"app.sgl.linker.iap.test.1","description":"test purchasing something","introPrice":null,"introPricePaymentMode":null,"billingPeriodUnit":"Day","countryCode":"US","introPricePeriodUnit":null,"discounts":[],"title":"SGL: Test purchase 1","price":"$0.99","billingPeriod":0,"group":null,"priceMicros":990000,"currency":"USD","introPricePeriod":null,"introPriceMicros":null}] invalid:[] } (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] INFO: bridge.loaded: {"validProducts":[{"id":"app.sgl.linker.iap.test.1","description":"test purchasing something","introPrice":null,"introPricePaymentMode":null,"billingPeriodUnit":"Day","countryCode":"US","introPricePeriodUnit":null,"discounts":[],"title":"SGL: Test purchase 1","price":"$0.99","billingPeriod":0,"group":null,"priceMicros":990000,"currency":"USD","introPricePeriod":null,"introPriceMicros":null}],"invalidProducts":[]} (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] INFO: eligibilities ready. (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] DEBUG: app.sgl.linker.iap.test.1 is valid: {"id":"app.sgl.linker.iap.test.1","description":"test purchasing something","introPrice":null,"introPricePaymentMode":null,"billingPeriodUnit":"Day","countryCode":"US","introPricePeriodUnit":null,"discounts":[],"title":"SGL: Test purchase 1","price":"$0.99","billingPeriod":0,"group":null,"priceMicros":990000,"currency":"USD","introPricePeriod":null,"introPriceMicros":null} (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] DEBUG: registering existing product (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] DEBUG: Products loaded: [{"className":"Product","title":"SGL: Test purchase 1","description":"test purchasing something","platform":"ios-appstore","type":"consumable","id":"app.sgl.linker.iap.test.1","offers":[{"className":"Offer","id":"$","pricingPhases":[{"price":"$0.99","priceMicros":990000,"currency":"USD","paymentMode":"UpFront","recurrenceMode":"NON_RECURRING"}],"productId":"app.sgl.linker.iap.test.1","productType":"consumable","platform":"ios-appstore","offerType":"Default"}],"raw":{"id":"app.sgl.linker.iap.test.1","description":"test purchasing something","introPrice":null,"introPricePaymentMode":null,"billingPeriodUnit":"Day","countryCode":"US","introPricePeriodUnit":null,"discounts":[],"title":"SGL: Test purchase 1","price":"$0.99","billingPeriod":0,"group":null,"priceMicros":990000,"currency":"USD","introPricePeriod":null,"introPriceMicros":null},"countryCode":"US"}] (user-script:13, line 321)
[Log] [CdvPurchase.Adapters] INFO: AppStore loaded: [{"className":"Product","title":"SGL: Test purchase 1","description":"test purchasing something","platform":"ios-appstore","type":"consumable","id":"app.sgl.linker.iap.test.1","offers":[{"className":"Offer","id":"$","pricingPhases":[{"price":"$0.99","priceMicros":990000,"currency":"USD","paymentMode":"UpFront","recurrenceMode":"NON_RECURRING"}],"productId":"app.sgl.linker.iap.test.1","productType":"consumable","platform":"ios-appstore","offerType":"Default"}],"raw":{"id":"app.sgl.linker.iap.test.1","description":"test purchasing something","introPrice":null,"introPricePaymentMode":null,"billingPeriodUnit":"Day","countryCode":"US","introPricePeriodUnit":null,"discounts":[],"title":"SGL: Test purchase 1","price":"$0.99","billingPeriod":0,"group":null,"priceMicros":990000,"currency":"USD","introPricePeriod":null,"introPriceMicros":null},"countryCode":"US"}] (user-script:13, line 321)
[Log] -IAP-: AppStore users can make payments (main.js, line 1)
[Log] -IAP-: checking app store redemption sheet... (main.js, line 1)
[Log] -IAP-: Store initialize done... (main.js, line 1)
[Log] [CdvPurchase.AppleAppStore.Bridge] DEBUG: processing pending transactions (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] DEBUG: loading appstore receipt... (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore.Bridge] DEBUG: loading appStoreReceipt (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore.Bridge] DEBUG: infoPlist: app.lostseraph.linker,1.0,16809984,null (user-script:13, line 321)
[Log] [CdvPurchase.AppleAppStore] DEBUG: appstore receipt loaded (user-script:13, line 321)
[Warning] [CdvPurchase.AppleAppStore] WARNING: no appStoreReceipt (user-script:13, line 321)
[Log] -IAP-: running update purchases... (main.js, line 1)
...
< redacted PI related logs >
...
[Log] -IAP-:  (main.js, line 1)
TESTS:
____________________________
list: false
actual product: undefined
test product: undefined```

should I attach my iap connection logic?

**Comment by jmdjr** [comment]
it ends up allowing the appstore to initialize and the appstore is available, but the list is still empty and trying to get a product is undefined.

**Comment by jmdjr** [comment]
I have a MVP of the project (takes out all the wrapping stuff and just the iap, which still doesn't connect. if that would be helpful?
[LinkerMVP_Purchasing.zip](https://github.com/j3k0/cordova-plugin-purchase/files/11012929/LinkerMVP_Purchasing.zip)

**Comment by jmdjr** [comment]
hrm... that is odd. it would explain why my particular project isn't working while others are just fine, if that is the case.  but I take it the mvp project helps?

**Comment by j3k0** [comment]
MVP helps, because it allows to reproduce the issue.

**Comment by j3k0** [comment]
Look, the 2 "CdvPurchase.store" instance have different types:

<img width="239" alt="Screenshot 2023-03-20 at 18 49 05" src="https://user-images.githubusercontent.com/191881/226411157-9c890cf3-4927-4073-80bf-306a6977d965.png">

One is "Store" the other is "F", I guess the second one is from a minified version of the same code while the first is the non-minified version. So the problem definitely isn't with the plugin, just that you somehow bundle and load the code twice.

**Comment by jmdjr** [comment]
I see how that can be troublesome... odd. I don't know why I am loading the unminified version and the minified version at the same time...

**Comment by jmdjr** [comment]
ah. ok. armed with that I can look to see how to break the double loading. thank you for your hard work!

**Comment by j3k0** [comment]
Maybe there's something I could do in the plugin to distribute it in a way
that better suits your case. Let me know. I keep digging a little on your
issue.

**Comment by jmdjr** [comment]
will do. I don't know how I double loaded the code, will try some unloading/reloading methods to see. seems like an edge case but if it helps make your codebase more resilient, maybe some minor reworking would be good.

**Comment by jmdjr** [comment]
```
⚡️  [log] - [LostSeraph] [-IAP-]: CdvPurchase IS defined

⚡️  [log] - [LostSeraph] [-IAP-]: installing iaptic receipt validator...

⚡️  [error] - ERROR Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'this.store.log')

Iaptic@user-script:13:104:34

@capacitor://www.lostseraph.com/main.js:1:646682

onInvoke@capacitor://www.lostseraph.com/main.js:1:87039

run@capacitor://www.lostseraph.com/polyfills.js:1:1920

@capacitor://www.lostseraph.com/polyfills.js:1:16761

onInvokeTask@capacitor://www.lostseraph.com/main.js:1:86859

runTask@capacitor://www.lostseraph.com/polyfills.js:1:2541

_@capacitor://www.lostseraph.com/polyfills.js:1:9190
```

trying the updated input and pushed to device, this is the result.

**Comment by j3k0** [comment]
Oh yeah, maybe because I made this change to your code's checkReady as
well:

  async checkReady() {
    return new Promise<void>(resolve => {
      const wait = () => {
        if(!window.CdvPurchase || !window.CdvPurchase.store) {


(added || !window.CdvPurchase.store)

**Comment by j3k0** [comment]
And make sure to remove the cordova-pluing-purchase import from iapCatalog as well

**Comment by jmdjr** [comment]
did that. added your extra check... still the same exception...

**Comment by jmdjr** [comment]
with the setup you provided
```
> window.CdvPurchase.store
< Store {0: "QUIET", 1: "ERROR", 2: "WARNING", 3: "INFO", 4: "DEBUG", 6777001: "SETUP", 6777002: "LOAD", 6777003: "PURCHASE", 6777004: "LOAD_RECEIPTS", 6777005: "CLIENT_INVALID", …}
> window._CdvPurchase.store
< TypeError: undefined is not an object (evaluating 'window._CdvPurchase.store')
```

**Comment by j3k0** [comment]
My edited project, works fine here (notice I changed app ID in XCode project, might have to be reverted to your own).
[LinkerMVP_Purchasing_Edited.zip](https://github.com/j3k0/cordova-plugin-purchase/files/11022033/LinkerMVP_Purchasing_Edited.zip)

**Comment by j3k0** [comment]
`window._CdvPurchase.store` will be undefined unless you stored `window._CdvPurchase` somewhere in your code.

**Comment by jmdjr** [comment]
will try it :D... and ha. ok.

**Comment by jmdjr** [comment]
OK! whatever you did it works on your version. so now I get to find the differences between that edited and my local one. yay!
thank you.

**Comment by jmdjr** [comment]
is the purchase supposed to show a confirmation before popping up the customary apple purchase dialog? I am only seeing the "type Y for purchase" and not the actual in-app purchase view.
